version: '3.3'

services:
  db:
   image: mysql:5.7
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: myrootpassword
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypassword
  
  app:
   depends_on:
    - migration
   build: .
   ports:
    - "8000:8000"
   restart: always
   environment:
    MYSQL_HOST: db:3306
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypassword

  migration:
   depends_on:
    - db
   build: .
   image: app
   restart: always
   command: php artisan -vvv migrate --force
   environment:
    MYSQL_HOST: db:3306
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypassword
